// Local demo only; all external requests and Holded calls are blocked.
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const require=createRequire(process.env.PLAYWRIGHT_PACKAGE||import.meta.url);
const {chromium}=require('playwright');
const browser=await chromium.launch({channel:'msedge',headless:true});
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  let holdedCalls=0;
  await page.route('**/*',route=>route.request().url().startsWith('http://127.0.0.1:5184/')?route.continue():route.abort());
  await page.route('**/api/holded/**',route=>{holdedCalls++;return route.abort()});
  await page.goto('http://127.0.0.1:5184/');
  await page.getByRole('button',{name:'Facturación',exact:true}).click();
  const notice=page.getByRole('button',{name:'Entendido',exact:true});
  if(await notice.count())await notice.click();
  const open=()=>page.getByRole('button',{name:'Editar BOR-2026-0044',exact:true}).click();
  await open();
  const modal=page.locator('.invoice-detail-modal');
  const rows=modal.locator('.invoice-line-row');
  const before=await rows.count();
  assert.ok(before>1,'A standard tariff line must be present');
  const row=rows.nth(1);
  const originalItem=await row.getByLabel('Item',{exact:true}).inputValue();
  await row.getByLabel('Precio',{exact:true}).fill('123.45');
  await row.locator('textarea').fill('4 BOXES - PRECIO ACORDADO');
  await row.getByLabel('Uds.',{exact:true}).fill('2');
  assert.equal(await row.getByLabel('Precio',{exact:true}).inputValue(),'123.45');
  await modal.locator('input[name="cliente"]').focus();
  await modal.locator('input[name="concepto"]').focus();
  assert.equal(await row.getByLabel('Precio',{exact:true}).inputValue(),'123.45','Client blur must not reprice');
  await modal.getByRole('button',{name:'Guardar borrador',exact:true}).click();
  await modal.waitFor({state:'hidden'});
  await open();
  assert.equal(await rows.count(),before);
  assert.equal(await row.getByLabel('Item',{exact:true}).inputValue(),originalItem);
  assert.equal(await row.getByLabel('Precio',{exact:true}).inputValue(),'123.45');
  assert.equal(await row.getByLabel('Uds.',{exact:true}).inputValue(),'2');
  assert.equal(await row.locator('textarea').inputValue(),'4 BOXES - PRECIO ACORDADO');
  await row.getByLabel('Precio',{exact:true}).fill('0');
  await row.getByLabel('Uds.',{exact:true}).fill('0');
  await modal.getByRole('button',{name:'Guardar borrador',exact:true}).click();
  await modal.waitFor({state:'hidden'});
  await page.getByRole('button',{name:'Dashboard',exact:true}).click();
  await page.getByRole('button',{name:'Facturación',exact:true}).click();
  if(await notice.count())await notice.click();
  await open();
  assert.equal(await row.getByLabel('Precio',{exact:true}).inputValue(),'0');
  assert.equal(await row.getByLabel('Uds.',{exact:true}).inputValue(),'0');
  assert.equal(await rows.count(),before);
  assert.equal(holdedCalls,0);
  assert.deepEqual(errors,[]);
  console.log('OK: standard tariff price, details, units, client blur, save/reopen, zero price/units and billing remount preserve manual edits; no Holded calls.');
} finally {await browser.close();}
