export const expedientesIniciales = [
  {id:'SW-2026-0048', buque:'MONTE EXPRESS', cliente:'UME Shipping', puerto:'Algeciras', eta:'02 Jul · 08:00', estado:'En curso', prioridad:'Alta', conductor:'Moisés R.', servicios:['Transporte','Entrega a bordo','POD'], bultos:2, peso:'680 kg', progreso:72, siguiente:'Confirmar acceso al muelle', aduana:'Liberado'},
  {id:'SW-2026-0047', buque:'POLARIS MILA', cliente:'Limani', puerto:'Tarragona', eta:'01 Jul · 18:00', estado:'Bloqueado', prioridad:'Urgente', conductor:'Sin asignar', servicios:['Recepción','Storage','Aduanas'], bultos:4, peso:'1.240 kg', progreso:38, siguiente:'Recibir autorización de Aduanas', aduana:'Pendiente'},
  {id:'SW-2026-0046', buque:'VIKING SEA', cliente:'A-Ships', puerto:'Barcelona', eta:'30 Jun · 11:00', estado:'Planificado', prioridad:'Media', conductor:'Javier S.', servicios:['Recogida aeropuerto','Transporte'], bultos:1, peso:'95 kg', progreso:54, siguiente:'Recogida en BCN T1', aduana:'No aplica'},
  {id:'SW-2026-0045', buque:'ATLANTIC STAR', cliente:'BlueWave Marine', puerto:'Valencia', eta:'03 Jul · 06:30', estado:'Nuevo', prioridad:'Media', conductor:'Clara V.', servicios:['Recepción','Transporte','POD'], bultos:7, peso:'2.100 kg', progreso:18, siguiente:'Validar packing list', aduana:'Documentación'},
  {id:'SW-2026-0044', buque:'OCEAN BREEZE', cliente:'UME Shipping', puerto:'Bilbao', eta:'29 Jun · 21:00', estado:'Completado', prioridad:'Baja', conductor:'Andrés M.', servicios:['Entrega a bordo','POD'], bultos:2, peso:'420 kg', progreso:100, siguiente:'Listo para facturar', aduana:'Liberado'}
];
export const movimientosAlmacen = [
  {ref:'ALM-318', expediente:'SW-2026-0047', buque:'POLARIS MILA', zona:'B-04', entrada:'29 Jun · 14:35', bultos:4, peso:'1.240 kg', dias:1, estado:'Retenido'},
  {ref:'ALM-317', expediente:'SW-2026-0048', buque:'MONTE EXPRESS', zona:'A-12', entrada:'29 Jun · 09:20', bultos:2, peso:'680 kg', dias:1, estado:'Preparado'},
  {ref:'ALM-315', expediente:'SW-2026-0045', buque:'ATLANTIC STAR', zona:'C-02', entrada:'27 Jun · 16:10', bultos:7, peso:'2.100 kg', dias:3, estado:'En stock'},
  {ref:'ALM-309', expediente:'SW-2026-0044', buque:'OCEAN BREEZE', zona:'SAL-01', entrada:'26 Jun · 08:15', bultos:2, peso:'420 kg', dias:0, estado:'Expedido'}
];
export const transportesIniciales = [
  {id:'TR-1042', expediente:'SW-2026-0046', ruta:'Aeropuerto BCN → Puerto Barcelona', hora:'Hoy · 09:15', conductor:'Javier S.', vehiculo:'7462 MRL', estado:'En ruta'},
  {id:'TR-1043', expediente:'SW-2026-0048', ruta:'Almacén Swiftport → Muelle Isla Verde', hora:'Mañana · 06:45', conductor:'Moisés R.', vehiculo:'2198 KPV', estado:'Asignado'},
  {id:'TR-1044', expediente:'SW-2026-0047', ruta:'Almacén Swiftport → Puerto Tarragona', hora:'Mañana · 15:30', conductor:'Sin asignar', vehiculo:'—', estado:'Sin asignar'},
  {id:'TR-1039', expediente:'SW-2026-0044', ruta:'Puerto Bilbao → Almacén cliente', hora:'Ayer · 20:10', conductor:'Andrés M.', vehiculo:'5031 LBD', estado:'Entregado'}
];
export const proveedoresIniciales = [
  {id:'PRV-001',nombre:'Swiftport Logistic',contacto:'Operaciones propias',telefono:'',activo:true},
  {id:'PRV-002',nombre:'Transportes del Estrecho',contacto:'Tráfico',telefono:'',activo:true},
  {id:'PRV-003',nombre:'Mediterránea Cargo',contacto:'Operaciones',telefono:'',activo:true}
];
export const eventosCalendarioIniciales = [
  {id:'EV-1001',titulo:'Recogida aeropuerto BCN',tipoServicio:'Transporte',fecha:'2026-06-29',inicio:'09:15',fin:'10:30',asignado:'Sin asignar',expediente:'SW-2026-0046',transporte:'TR-1042',color:'blue'},
  {id:'EV-1002',titulo:'Recepción de mercancía',tipoServicio:'Recepción',fecha:'2026-06-29',inicio:'14:30',fin:'15:30',asignado:'Sin asignar',expediente:'SW-2026-0047',transporte:'',color:'teal'},
  {id:'EV-1003',titulo:'Entrega Puerto Tarragona',tipoServicio:'Transporte',fecha:'2026-06-30',inicio:'15:30',fin:'17:00',asignado:'Sin asignar',expediente:'SW-2026-0047',transporte:'TR-1044',color:'orange'},
  {id:'EV-1004',titulo:'Entrega a bordo',tipoServicio:'Transporte',fecha:'2026-07-01',inicio:'06:45',fin:'08:15',asignado:'Sin asignar',expediente:'SW-2026-0048',transporte:'TR-1043',color:'purple'}
];
export const tramitesAduana = [
  {id:'AD-882', expediente:'SW-2026-0047', tipo:'T1', referencia:'T1ES0060218842', limite:'Hoy · 17:00', estado:'Pendiente', nota:'Falta autorización del consignatario'},
  {id:'AD-881', expediente:'SW-2026-0045', tipo:'DUA importación', referencia:'En preparación', limite:'02 Jul · 12:00', estado:'Documentación', nota:'Packing list recibido'},
  {id:'AD-879', expediente:'SW-2026-0048', tipo:'Levante', referencia:'CSV-81K2-P90', limite:'Completado', estado:'Liberado', nota:'Mercancía disponible'},
  {id:'AD-876', expediente:'SW-2026-0044', tipo:'T2L', referencia:'T2L-ES-9918', limite:'Completado', estado:'Liberado', nota:'Archivado en expediente'}
];
export const clientNames = ['UME Shipping','Limani','A-Ships','BlueWave Marine'];
export const holdedClientProfiles = [
  {
    codigo:'HLD-43000016',
    nombre:'NutriNexus',
    fiscalName:'NutriNexus',
    taxId:'',
    contacto:'',
    telefono:'',
    direccion:'España',
    condicionesPago:'Pendiente',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000016 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-43000014',
    nombre:'MEXICO EXPRESS',
    fiscalName:'MEXICO EXPRESS',
    taxId:'',
    contacto:'',
    telefono:'',
    direccion:'IMO: 9686900 · Italia',
    condicionesPago:'Pendiente',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000014 · revisar si es cliente o referencia de buque'
  },
  {
    codigo:'HLD-43000012',
    nombre:'ITALMAR',
    fiscalName:'ITALMAR',
    taxId:'',
    contacto:'',
    telefono:'',
    direccion:'España',
    condicionesPago:'Pendiente',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000012 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-43000011',
    nombre:'CONVECA',
    fiscalName:'CONVECA - CONSORCIO CONVECA II V&P',
    taxId:'20613400860',
    contacto:'nbastidas@conveca.net',
    telefono:'+58 412-2697832',
    direccion:'CALLE JUAN DE LA FUENTE NRO 760, MIRAFLORES, LIMA, Perú',
    condicionesPago:'Pendiente',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000011 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-43000009',
    nombre:'Grupo Nexus Network',
    fiscalName:'Grupo Nexus Network',
    taxId:'',
    contacto:'',
    telefono:'',
    direccion:'España',
    condicionesPago:'Pendiente',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000009 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-43000010',
    nombre:'ALS - ALGECIRAS LOGISTICS SOLUTION',
    fiscalName:'ALS - ALGECIRAS LOGISTICS SOLUTION',
    taxId:'B72058449',
    contacto:'',
    telefono:'',
    direccion:'POL IND LA MENACHA AVDA DE LA BAHIA PARC 14, 11204 ALGECIRAS, Cádiz, España',
    condicionesPago:'Pendiente',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000010 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-43000008',
    nombre:'VILAR NAVAL ARCHITECTS SLU',
    fiscalName:'VILAR NAVAL ARCHITECTS SLU',
    taxId:'B09694332',
    contacto:'',
    telefono:'',
    direccion:'España',
    condicionesPago:'Pendiente',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000008 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-43000007',
    nombre:'MARINE LOGISTICS ESPAÑA S.L.',
    fiscalName:'MARINE LOGISTICS ESPAÑA,S.L.',
    taxId:'B72204993',
    contacto:'logistics.algercias@marinelogistics.eu',
    telefono:'956 787 223',
    direccion:'CTRA. CADIZ - MALAGA KM.107, EDF. SOTOVILLA, OFICINA 2-11, 11205 ALGECIRAS, Cádiz, España',
    condicionesPago:'Transferencia bancaria',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000007 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-43000006',
    nombre:'UME Shipping',
    fiscalName:'UME SHIPPING AB',
    taxId:'556989-1111',
    contacto:'',
    telefono:'',
    direccion:'Box 5216 (Nybrogatan 34), 10245 Stockholm, Stockholm, Suecia',
    condicionesPago:'Pendiente',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000006 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-43000004',
    nombre:'A-Ships',
    fiscalName:'GALAXY SEAWAYS SA',
    taxId:'RN 78926',
    contacto:'operations@a-ships.com',
    telefono:'',
    direccion:'TRUST COMPANY COMPLEX / AJELTAKE ROAD - AJELTAKE ISLAND, MAJURO, Islas Marshall',
    condicionesPago:'Transferencia bancaria',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000004 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-40000092',
    nombre:'Limani',
    fiscalName:'LIMANI SUPPLY GROUP S.L.',
    taxId:'ESB01785120',
    contacto:'e-invoice@limanisupply.com',
    telefono:'',
    direccion:'Calle Juan de la Cierva 11, 28810 Villalbilla, Madrid, España',
    condicionesPago:'Transferencia bancaria',
    moneda:'EUR',
    tarifaActiva:'LIMANI Barcelona 2026',
    recepcion:'0-35 kg 15€ · 35-250 kg 60€ · 251-500 kg 130€ · 501-2500 kg 245€',
    storage:'0-35 kg gratis · 36-100 kg 5€/día · 101-500 kg 10€/día · 500+ kg 15€/día',
    transporte:'Warehouse→Vessel: 45€ / 95€ / 250€ / 350€ por peso',
    recargo:'+30% overtime / holidays',
    notas:'Importado de Holded · cuenta 40000092 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-43000003',
    nombre:'OCA GLOBAL',
    fiscalName:'OCA GLOBAL MARINE AND CARGO SURVERYORS, S.L.U',
    taxId:'B20591194',
    contacto:'suppliers.marine@ocaglobal.com',
    telefono:'',
    direccion:'VIA DE LAS DOS CASTILLAS 7, 28224 POZUELO, Madrid, España',
    condicionesPago:'Transferencia bancaria',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000003 · régimen general · modelo 347: sí'
  },
  {
    codigo:'HLD-43000001',
    nombre:'BALEARIA',
    fiscalName:'BALEARIA EUROLINES MARITIMAS SA',
    taxId:'A53293213',
    contacto:'consignaciones.barcelona@balearia.com',
    telefono:'630 87 10 22',
    direccion:'ESTACION MARITIMA S/N, 03700 Denia, Alicante, España',
    condicionesPago:'Transferencia bancaria',
    moneda:'EUR',
    tarifaActiva:'Sin tarifa automática',
    recepcion:'Pendiente de tarifa',
    storage:'Pendiente de tarifa',
    transporte:'Pendiente de tarifa',
    recargo:'Pendiente',
    notas:'Importado de Holded · cuenta 43000001 · régimen general · modelo 347: sí'
  }
];
export const timeline = [
  {hora:'09:12', titulo:'Solicitud recibida', detalle:'Email registrado en el expediente', estado:'done'},
  {hora:'09:30', titulo:'Expediente creado', detalle:'Servicios y tarifa aplicados', estado:'done'},
  {hora:'10:05', titulo:'Consignatario contactado', detalle:'Acceso al muelle solicitado', estado:'done'},
  {hora:'14:35', titulo:'Mercancía recibida', detalle:'2 bultos ubicados en A-12', estado:'done'},
  {hora:'06:45', titulo:'Transporte al puerto', detalle:'Planificado para mañana', estado:'next'},
  {hora:'—', titulo:'Entrega a bordo y POD', detalle:'Pendiente de ejecución', estado:'pending'}
];
